package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsFriendsCircle;
import com.qiguliuxing.dts.db.domain.DtsFriendsCircleExample;
import com.qiguliuxing.dts.db.domain.DtsFriendsCircleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsFriendsCircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    long countByExample(DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int deleteByExample(DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int insert(DtsFriendsCircleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int insertSelective(DtsFriendsCircleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFriendsCircle selectOneByExample(DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFriendsCircleWithBLOBs selectOneByExampleSelective(@Param("example") DtsFriendsCircleExample example, @Param("selective") DtsFriendsCircleWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFriendsCircleWithBLOBs selectOneByExampleWithBLOBs(DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsFriendsCircleWithBLOBs> selectByExampleSelective(@Param("example") DtsFriendsCircleExample example, @Param("selective") DtsFriendsCircleWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    List<DtsFriendsCircleWithBLOBs> selectByExampleWithBLOBs(DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    List<DtsFriendsCircle> selectByExample(DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFriendsCircleWithBLOBs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsFriendsCircleWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    DtsFriendsCircleWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsFriendsCircleWithBLOBs record, @Param("example") DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DtsFriendsCircleWithBLOBs record, @Param("example") DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsFriendsCircle record, @Param("example") DtsFriendsCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsFriendsCircleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DtsFriendsCircleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_friends_circle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsFriendsCircle record);
}